version: '3.9'

services:
  api:
    build: .
    container_name: node-lg-api
    ports:
      - '3000:3000'
    environment:
      - DB_SERVER=mssql
      - DB_USER=sa
      - DB_PASSWORD=MystrongPassword
      - DB_DATABASE=Dev
      - DB_PORT=1433
      - PORT=3000
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: YourStrong@Passw0rd
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
